Solution node_accounting-app-with-db
mate-academy/node_accounting-app-with-db pull request #124
Opened 2023-10-02 17:30 UTC by NazariiAlieksieiev

2023-10-02 17:52 UTC, Andriy-Shymkiv requested changes
please delete all eslint blockers comments from your code

2023-10-02 17:52 UTC, Andriy-Shymkiv commented on src/controllers/expenses.controllers.js
> +/* eslint-disable no-console */
removing eslint rules is not a good idea, please delete

2023-10-02 17:52 UTC, Andriy-Shymkiv commented on src/controllers/expenses.controllers.js
maybe `expenses.controller.js` ? because it is one controller)

2023-10-02 17:52 UTC, Andriy-Shymkiv commented on src/controllers/expenses.controllers.js
> +  res.send(expensesServices.normalize(newExpense));
you can return newExpense from `updateExpense` function and do the following:
```suggestion
  const newExpense = await expensesServices.updateExpense(id, newValues);
  res.send(expensesServices.normalize(newExpense));
```

2023-10-02 17:52 UTC, Andriy-Shymkiv commented on src/controllers/expenses.controllers.js
> +  res.send(expensesServices.normalize(newExpense));
just do not forget to return it from `updateExpense`

2023-10-02 17:52 UTC, Andriy-Shymkiv commented on src/controllers/users.controllers.js
> +/* eslint-disable space-before-function-paren */
same here. please delete it

2023-10-02 17:52 UTC, Andriy-Shymkiv commented on src/controllers/users.controllers.js
> +  res.send(usersServices.normalizeUser(updatedTodo));
you can do the same as with expenses

2023-10-02 17:52 UTC, Andriy-Shymkiv commented on src/controllers/users.controllers.js
> +  res.send(usersServices.normalizeUser(updatedTodo));
and what is `updatedTodo`? 😃

2023-10-02 17:52 UTC, Andriy-Shymkiv commented on src/services/expenses.services.js
> +};
I really don't understand what's the purpose of this function? it is take and return the same type of data. please explain me

2023-10-02 17:52 UTC, Andriy-Shymkiv commented on src/services/expenses.services.js
> +};
why don't you just:
```suggestion
const createExpense = async (newExpense) => {
  return Expense.create(newExpense);
};
```

2023-10-02 17:52 UTC, Andriy-Shymkiv commented on src/services/expenses.services.js
> +};
isn't that the same?

2023-10-03 07:49 UTC, DarkMistyRoom approved these changes
Good job! Check the comments

2023-10-03 07:49 UTC, DarkMistyRoom commented on src/services/users.service.js
> +});
better move it to a separate file

2023-10-03 07:49 UTC, DarkMistyRoom commented on src/services/expenses.service.js
> +};
you can use `where` to get only needed items

2023-10-03 07:49 UTC, DarkMistyRoom commented on src/controllers/expenses.controller.js
> +    expenses = await expensesServices.getAllExpenses();
in a real project, you need to handle all possible errors. So wrap in `try catch` all code where an Error can appear

2024-07-27 10:56 UTC, closed without merging